// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: integrity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetDatahashRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDatahashRequest) Reset()         { *m = QueryGetDatahashRequest{} }
func (m *QueryGetDatahashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDatahashRequest) ProtoMessage()    {}
func (*QueryGetDatahashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0a8abfb300a230, []int{0}
}
func (m *QueryGetDatahashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDatahashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDatahashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDatahashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDatahashRequest.Merge(m, src)
}
func (m *QueryGetDatahashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDatahashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDatahashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDatahashRequest proto.InternalMessageInfo

func (m *QueryGetDatahashRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetDatahashResponse struct {
	Datahash *Datahash `protobuf:"bytes,1,opt,name=Datahash,proto3" json:"Datahash,omitempty"`
}

func (m *QueryGetDatahashResponse) Reset()         { *m = QueryGetDatahashResponse{} }
func (m *QueryGetDatahashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDatahashResponse) ProtoMessage()    {}
func (*QueryGetDatahashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0a8abfb300a230, []int{1}
}
func (m *QueryGetDatahashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDatahashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDatahashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDatahashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDatahashResponse.Merge(m, src)
}
func (m *QueryGetDatahashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDatahashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDatahashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDatahashResponse proto.InternalMessageInfo

func (m *QueryGetDatahashResponse) GetDatahash() *Datahash {
	if m != nil {
		return m.Datahash
	}
	return nil
}

type QueryAllDatahashRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDatahashRequest) Reset()         { *m = QueryAllDatahashRequest{} }
func (m *QueryAllDatahashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDatahashRequest) ProtoMessage()    {}
func (*QueryAllDatahashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0a8abfb300a230, []int{2}
}
func (m *QueryAllDatahashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDatahashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDatahashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDatahashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDatahashRequest.Merge(m, src)
}
func (m *QueryAllDatahashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDatahashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDatahashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDatahashRequest proto.InternalMessageInfo

func (m *QueryAllDatahashRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDatahashResponse struct {
	Datahash   []*Datahash         `protobuf:"bytes,1,rep,name=Datahash,proto3" json:"Datahash,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDatahashResponse) Reset()         { *m = QueryAllDatahashResponse{} }
func (m *QueryAllDatahashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDatahashResponse) ProtoMessage()    {}
func (*QueryAllDatahashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0a8abfb300a230, []int{3}
}
func (m *QueryAllDatahashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDatahashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDatahashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDatahashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDatahashResponse.Merge(m, src)
}
func (m *QueryAllDatahashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDatahashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDatahashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDatahashResponse proto.InternalMessageInfo

func (m *QueryAllDatahashResponse) GetDatahash() []*Datahash {
	if m != nil {
		return m.Datahash
	}
	return nil
}

func (m *QueryAllDatahashResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetDatahashRequest)(nil), "SBC.integrity.integrity.QueryGetDatahashRequest")
	proto.RegisterType((*QueryGetDatahashResponse)(nil), "SBC.integrity.integrity.QueryGetDatahashResponse")
	proto.RegisterType((*QueryAllDatahashRequest)(nil), "SBC.integrity.integrity.QueryAllDatahashRequest")
	proto.RegisterType((*QueryAllDatahashResponse)(nil), "SBC.integrity.integrity.QueryAllDatahashResponse")
}

func init() { proto.RegisterFile("integrity/query.proto", fileDescriptor_2b0a8abfb300a230) }

var fileDescriptor_2b0a8abfb300a230 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x4a, 0xfb, 0x40,
	0x14, 0xc6, 0x3b, 0xf9, 0x5f, 0x90, 0x29, 0xb8, 0x18, 0x90, 0x96, 0x22, 0xc1, 0x46, 0xa8, 0x6d,
	0x17, 0x33, 0xb6, 0xae, 0x5d, 0xf4, 0x82, 0xdd, 0x6a, 0xbb, 0xd2, 0xdd, 0xa4, 0x19, 0xd2, 0x81,
	0x34, 0x93, 0x76, 0xa6, 0x62, 0x11, 0x37, 0x3e, 0x81, 0xe0, 0x5a, 0x04, 0x9f, 0x46, 0x77, 0x05,
	0x37, 0x2e, 0xa5, 0xf5, 0x41, 0xa4, 0x49, 0xda, 0xf4, 0x4a, 0xe8, 0x6e, 0xc8, 0x39, 0xdf, 0x77,
	0x7e, 0x5f, 0xce, 0x0c, 0x3c, 0xe0, 0xae, 0x62, 0x76, 0x9f, 0xab, 0x21, 0xe9, 0x0d, 0x58, 0x7f,
	0x88, 0xbd, 0xbe, 0x50, 0x02, 0xa5, 0x5a, 0xd5, 0x1a, 0x9e, 0x97, 0xa2, 0x53, 0xe6, 0xd0, 0x16,
	0xc2, 0x76, 0x18, 0xa1, 0x1e, 0x27, 0xd4, 0x75, 0x85, 0xa2, 0x8a, 0x0b, 0x57, 0x06, 0xb2, 0x4c,
	0xb1, 0x2d, 0x64, 0x57, 0x48, 0x62, 0x52, 0xc9, 0x02, 0x3f, 0x72, 0x5b, 0x32, 0x99, 0xa2, 0x25,
	0xe2, 0x51, 0x9b, 0xbb, 0x7e, 0x73, 0xd8, 0x9b, 0x8e, 0x26, 0x5b, 0x54, 0xd1, 0x0e, 0x95, 0x9d,
	0xa0, 0x62, 0x14, 0x60, 0xea, 0x6a, 0xaa, 0x6d, 0x30, 0x55, 0x0f, 0x2b, 0x4d, 0xd6, 0x1b, 0x30,
	0xa9, 0xd0, 0x3e, 0xd4, 0xb8, 0x95, 0x06, 0x47, 0x20, 0xff, 0xb7, 0xa9, 0x71, 0xcb, 0xb8, 0x86,
	0xe9, 0xf5, 0x56, 0xe9, 0x09, 0x57, 0x32, 0x74, 0x0e, 0xf7, 0x66, 0xdf, 0x7c, 0x45, 0xb2, 0x9c,
	0xc5, 0x5b, 0x62, 0xe1, 0xb9, 0x78, 0x2e, 0x31, 0x68, 0x48, 0x51, 0x71, 0x9c, 0x55, 0x8a, 0x0b,
	0x08, 0xa3, 0x38, 0xa1, 0x77, 0x0e, 0x07, 0xd9, 0xf1, 0x34, 0x3b, 0x0e, 0xfe, 0x65, 0x98, 0x1d,
	0x5f, 0x52, 0x9b, 0x85, 0xda, 0xe6, 0x82, 0xd2, 0x78, 0x03, 0x21, 0xfe, 0xd2, 0x8c, 0x8d, 0xf8,
	0x7f, 0x76, 0xc4, 0x47, 0x8d, 0x25, 0x46, 0xcd, 0x67, 0x3c, 0x89, 0x65, 0x0c, 0x66, 0x2f, 0x42,
	0x96, 0x3f, 0x34, 0xf8, 0xcf, 0x87, 0x44, 0xaf, 0x20, 0x42, 0x42, 0xa7, 0x5b, 0x61, 0xb6, 0xec,
	0x2e, 0x53, 0xda, 0x41, 0x11, 0x70, 0x18, 0xf8, 0xf1, 0xf3, 0xe7, 0x59, 0xcb, 0xa3, 0x1c, 0x69,
	0x55, 0x6b, 0x24, 0xba, 0x30, 0xeb, 0x57, 0x87, 0xdc, 0x73, 0xeb, 0x01, 0xbd, 0x00, 0x98, 0x9c,
	0x99, 0x54, 0x1c, 0x27, 0x0e, 0x72, 0x7d, 0xb5, 0x71, 0x90, 0x1b, 0x16, 0x65, 0x14, 0x7c, 0xc8,
	0x63, 0x94, 0x8d, 0x85, 0xac, 0xd6, 0xdf, 0xc7, 0x3a, 0x18, 0x8d, 0x75, 0xf0, 0x3d, 0xd6, 0xc1,
	0xd3, 0x44, 0x4f, 0x8c, 0x26, 0x7a, 0xe2, 0x6b, 0xa2, 0x27, 0x6e, 0x8a, 0x36, 0x57, 0x9d, 0x81,
	0x89, 0xdb, 0xa2, 0xbb, 0x62, 0x73, 0xb7, 0x70, 0x56, 0x43, 0x8f, 0x49, 0xf3, 0xbf, 0xff, 0x4c,
	0xce, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xad, 0x21, 0x35, 0x0f, 0xbc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a datahash by id.
	Datahash(ctx context.Context, in *QueryGetDatahashRequest, opts ...grpc.CallOption) (*QueryGetDatahashResponse, error)
	// Queries a list of datahash items.
	DatahashAll(ctx context.Context, in *QueryAllDatahashRequest, opts ...grpc.CallOption) (*QueryAllDatahashResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Datahash(ctx context.Context, in *QueryGetDatahashRequest, opts ...grpc.CallOption) (*QueryGetDatahashResponse, error) {
	out := new(QueryGetDatahashResponse)
	err := c.cc.Invoke(ctx, "/SBC.integrity.integrity.Query/Datahash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DatahashAll(ctx context.Context, in *QueryAllDatahashRequest, opts ...grpc.CallOption) (*QueryAllDatahashResponse, error) {
	out := new(QueryAllDatahashResponse)
	err := c.cc.Invoke(ctx, "/SBC.integrity.integrity.Query/DatahashAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a datahash by id.
	Datahash(context.Context, *QueryGetDatahashRequest) (*QueryGetDatahashResponse, error)
	// Queries a list of datahash items.
	DatahashAll(context.Context, *QueryAllDatahashRequest) (*QueryAllDatahashResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Datahash(ctx context.Context, req *QueryGetDatahashRequest) (*QueryGetDatahashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Datahash not implemented")
}
func (*UnimplementedQueryServer) DatahashAll(ctx context.Context, req *QueryAllDatahashRequest) (*QueryAllDatahashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatahashAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Datahash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDatahashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Datahash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SBC.integrity.integrity.Query/Datahash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Datahash(ctx, req.(*QueryGetDatahashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DatahashAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDatahashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DatahashAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SBC.integrity.integrity.Query/DatahashAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DatahashAll(ctx, req.(*QueryAllDatahashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SBC.integrity.integrity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Datahash",
			Handler:    _Query_Datahash_Handler,
		},
		{
			MethodName: "DatahashAll",
			Handler:    _Query_DatahashAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrity/query.proto",
}

func (m *QueryGetDatahashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDatahashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDatahashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDatahashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDatahashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDatahashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Datahash != nil {
		{
			size, err := m.Datahash.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDatahashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDatahashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDatahashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDatahashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDatahashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDatahashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Datahash) > 0 {
		for iNdEx := len(m.Datahash) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Datahash[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetDatahashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDatahashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Datahash != nil {
		l = m.Datahash.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDatahashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDatahashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Datahash) > 0 {
		for _, e := range m.Datahash {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetDatahashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDatahashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDatahashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDatahashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDatahashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDatahashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datahash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Datahash == nil {
				m.Datahash = &Datahash{}
			}
			if err := m.Datahash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDatahashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDatahashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDatahashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDatahashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDatahashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDatahashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datahash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Datahash = append(m.Datahash, &Datahash{})
			if err := m.Datahash[len(m.Datahash)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
